<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <LangVersion>latest</LangVersion><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks><TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild><AnalysisLevel>latest</AnalysisLevel><Deterministic>true</Deterministic>
    <Version>0.2.0-alpha.1</Version><Authors>PereLV</Authors><Product>Llampec</Product>
    <Copyright>Copyright (c) 2026 PereLV</Copyright>
    <RepositoryUrl>https://github.com/PereLV/Llampec</RepositoryUrl><PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
