using System.Globalization;

namespace Llampec.Settings;

/// <summary>Small, shared UI catalogue. Unknown text (for example monitor names) is preserved.</summary>
public static class UiText
{
    public static string Language { get; private set; } = "en";
    public static string ResolveLanguage(string? tag) => (tag ?? CultureInfo.CurrentUICulture.Name).Split('-')[0].ToLowerInvariant() switch
    { "es" => "es", "ca" => "ca", _ => "en" };
    public static void SetLanguage(string? tag) => Language = ResolveLanguage(tag);
    public static string Get(string text) => Translate(text, Language);
    public static string Translate(string text, string language) => Catalogue.TryGetValue(text, out var value)
        ? language switch { "es" => value.Es, "ca" => value.Ca, _ => text } : text;
    public static string Format(string text, params object[] values) => string.Format(CultureInfo.CurrentCulture, Get(text), values);
    public static IReadOnlyCollection<string> Keys => Catalogue.Keys;

    private static readonly Dictionary<string, (string Es, string Ca)> Catalogue = new(StringComparer.Ordinal)
    {
        ["Screenshot"] = ("Captura de pantalla", "Captura de pantalla"),
        ["Release modifier keys and try again."] = ("Suelta las teclas modificadoras y vuelve a intentarlo.", "Solta les tecles modificadores i torna-ho a provar."),
        ["Could not open Windows screen capture."] = ("No se ha podido abrir la captura de pantalla de Windows.", "No s'ha pogut obrir la captura de pantalla de Windows."),
        ["Logitech MX mouse"] = ("Ratón Logitech MX", "Ratolí Logitech MX"),
        ["Logitech HID++ feature code adapted from Mouser."] = ("Código de las funciones Logitech HID++ adaptado de Mouser.", "Codi de les funcions Logitech HID++ adaptat de Mouser."),
        ["Enable Logitech mouse settings"] = ("Activar los ajustes del ratón Logitech", "Activa la configuració del ratolí Logitech"),
        ["Mouse"] = ("Ratón", "Ratolí"),
        ["Scan and choose a mouse"] = ("Busca y elige un ratón", "Busca i tria un ratolí"),
        ["Find mice"] = ("Buscar ratones", "Busca ratolins"),
        ["Reconnect"] = ("Reconectar", "Reconnecta"),
        ["Set DPI"] = ("Ajustar DPI", "Ajusta els DPI"),
        ["Wheel mode"] = ("Modo de la rueda", "Mode de la roda"),
        ["Keep current setting"] = ("Mantener el ajuste actual", "Mantín la configuració actual"),
        ["Free spin"] = ("Giro libre", "Gir lliure"),
        ["Ratchet"] = ("Giro por pasos", "Gir per passos"),
        ["Automatic (SmartShift)"] = ("Automático (SmartShift)", "Automàtic (SmartShift)"),
        ["SmartShift threshold (1–254)"] = ("Umbral de SmartShift (1–254)", "Llindar de SmartShift (1–254)"),
        ["Invert vertical scrolling"] = ("Invertir el desplazamiento vertical", "Invertix el desplaçament vertical"),
        ["Invert horizontal scrolling"] = ("Invertir el desplazamiento horizontal", "Invertix el desplaçament horitzontal"),
        ["Changes are saved only when you press Apply. Reconnect uses the saved settings."] = ("Los cambios se guardan al pulsar Aplicar. Reconectar usa los ajustes guardados.", "Els canvis es guarden en prémer Aplica. Reconnecta usa la configuració guardada."),
        ["Mouse buttons"] = ("Botones del ratón", "Botons del ratolí"),
        ["Enter a shortcut such as Win+Tab or Ctrl+C. Leave empty to keep the original action."] = ("Introduce un atajo como Win+Tab o Ctrl+C. Deja el campo vacío para mantener la acción original.", "Introduïx una drecera com Win+Tab o Ctrl+C. Deixa el camp buit per a mantindre l'acció original."),
        ["Checked: inverted. Unchecked: normal. Dash: keep the current setting."] = ("Marcado: invertido. Sin marcar: normal. Guion: mantener el ajuste actual.", "Marcat: invertit. Sense marcar: normal. Guió: mantín la configuració actual."),
        ["Unavailable controls keep their saved values. Find mice again after connecting the mouse."] = ("Los controles no disponibles conservan sus valores guardados. Busca ratones de nuevo después de conectarlo.", "Els controls no disponibles conserven els valors guardats. Busca ratolins de nou després de connectar-lo."),
        ["Reconnecting with the saved settings."] = ("Reconectando con los ajustes guardados.", "Reconnectant amb la configuració guardada."),
        ["Looking for connected Logitech mice…"] = ("Buscando ratones Logitech conectados…", "Buscant ratolins Logitech connectats…"),
        ["No connected mouse found. Saved settings are kept."] = ("No se ha encontrado un ratón conectado. Se conservan los ajustes guardados.", "No s'ha trobat un ratolí connectat. Es conserva la configuració guardada."),
        ["Choose a mouse, adjust its settings, then press Apply."] = ("Elige un ratón, configura sus opciones y pulsa Aplicar.", "Tria un ratolí, configura les opcions i prem Aplica."),
        ["Could not inspect the mouse."] = ("No se ha podido consultar el ratón.", "No s'ha pogut consultar el ratolí."),
        ["Saved mouse (not connected)"] = ("Ratón guardado (sin conexión)", "Ratolí guardat (sense connexió)"),
        ["{0} · receiver slot {1}"] = ("{0} · posición {1} del receptor", "{0} · posició {1} del receptor"),
        ["Thumb button"] = ("Pulsador del pulgar", "Polsador del polze"),
        ["Middle button"] = ("Botón central", "Botó central"),
        ["Back button"] = ("Botón Atrás", "Botó Enrere"),
        ["Forward button"] = ("Botón Adelante", "Botó Avant"),
        ["Wheel mode button"] = ("Botón del modo de la rueda", "Botó del mode de la roda"),
        ["Gesture button"] = ("Botón de gestos", "Botó de gestos"),
        ["DPI button"] = ("Botón de DPI", "Botó de DPI"),
        ["Mouse button {0}"] = ("Botón del ratón {0}", "Botó del ratolí {0}"),
        ["Not currently available"] = ("No disponible ahora", "No disponible ara"),
        ["Original action"] = ("Acción original", "Acció original"),
        ["Find a mouse to discover its buttons."] = ("Busca un ratón para consultar sus botones.", "Busca un ratolí per a consultar-ne els botons."),
        ["This mouse exposes no remappable buttons."] = ("Este ratón no ofrece botones reasignables.", "Este ratolí no oferix botons reassignables."),
        ["DPI: {0}–{1}, in steps of {2}. Current: {3}."] = ("DPI: {0}–{1}, en pasos de {2}. Actual: {3}.", "DPI: {0}–{1}, en passos de {2}. Actual: {3}."),
        ["Supported DPI: {0}. Current: {1}."] = ("DPI admitidos: {0}. Actual: {1}.", "DPI admesos: {0}. Actual: {1}."),
        ["DPI capability is unavailable. Saved DPI is kept."] = ("La función DPI no está disponible. Se conserva el valor guardado.", "La funció DPI no està disponible. Es conserva el valor guardat."),
        ["Choose a mouse before enabling its settings."] = ("Elige un ratón antes de activar sus ajustes.", "Tria un ratolí abans d'activar-ne la configuració."),
        ["Enter a supported whole-number DPI value."] = ("Introduce un valor DPI entero y compatible.", "Introduïx un valor DPI enter i compatible."),
        ["Enter a DPI value from the supported range and step, or the listed values."] = ("Introduce un DPI del rango y paso admitidos, o de los valores de la lista.", "Introduïx un DPI del rang i pas admesos, o dels valors de la llista."),
        ["Enter a whole number from 1 to 254."] = ("Introduce un número entero del 1 al 254.", "Introduïx un nombre enter de l'1 al 254."),
        ["Invalid shortcut for {0}. Use Win+Tab, Ctrl+C or F8."] = ("Atajo no válido para {0}. Usa Win+Tab, Ctrl+C o F8.", "Drecera no vàlida per a {0}. Usa Win+Tab, Ctrl+C o F8."),
        ["Saving mouse settings…"] = ("Guardando los ajustes del ratón…", "Guardant la configuració del ratolí…"),
        ["Mouse settings saved."] = ("Ajustes del ratón guardados.", "Configuració del ratolí guardada."),
        ["Could not apply mouse settings."] = ("No se han podido aplicar los ajustes del ratón.", "No s'ha pogut aplicar la configuració del ratolí."),
        ["Mouse settings are off."] = ("Los ajustes del ratón están desactivados.", "La configuració del ratolí està desactivada."),
        ["Connecting to the saved mouse…"] = ("Conectando con el ratón guardado…", "Connectant amb el ratolí guardat…"),
        ["Connected: {0}"] = ("Conectado: {0}", "Connectat: {0}"),
        ["Mouse settings are paused while Windows sleeps."] = ("Los ajustes del ratón están en pausa mientras Windows está suspendido.", "La configuració del ratolí està en pausa mentres Windows està suspés."),
        ["Mouse settings could not be applied."] = ("No se han podido aplicar los ajustes del ratón.", "No s'ha pogut aplicar la configuració del ratolí."),
        ["Waiting for the saved mouse. Settings will resume when it reconnects."] = ("Esperando al ratón guardado. Los ajustes se reanudarán cuando se reconecte.", "Esperant el ratolí guardat. La configuració es reprendrà quan es reconnecte."),
        ["Restoration is pending. Reconnect the same mouse before changing devices."] = ("Hay una restauración pendiente. Reconecta el mismo ratón antes de cambiar de dispositivo.", "Hi ha una restauració pendent. Reconnecta el mateix ratolí abans de canviar de dispositiu."),
        ["Logitech mouse support is unavailable. Restart Llampec and try again."] = ("La función de ratón Logitech no está disponible. Reinicia Llampec e inténtalo de nuevo.", "La funció de ratolí Logitech no està disponible. Reinicia Llampec i torna a provar-ho."),
        ["Select a Logitech mouse before enabling its settings."] = ("Selecciona un ratón Logitech antes de activar sus ajustes.", "Selecciona un ratolí Logitech abans d'activar-ne la configuració."),
        ["The receiver slot must be 1–6, or 255 for a directly connected mouse."] = ("La posición del receptor debe estar entre 1 y 6, o ser 255 para una conexión directa.", "La posició del receptor ha d'estar entre 1 i 6, o ser 255 per a una connexió directa."),
        ["The mouse unit ID must contain eight hexadecimal digits."] = ("El identificador del ratón debe contener ocho dígitos hexadecimales.", "L'identificador del ratolí ha de contindre huit dígits hexadecimals."),
        ["Select a receiver mouse with a stable unit ID before enabling its settings."] = ("Selecciona un ratón cuyo receptor permita identificarlo de forma estable antes de activar sus ajustes.", "Selecciona un ratolí que el receptor permeta identificar de manera estable abans d'activar-ne la configuració."),
        ["DPI must be greater than zero."] = ("El valor DPI debe ser mayor que cero.", "El valor DPI ha de ser major que zero."),
        ["Wheel mode must be free, ratchet, auto, or unspecified."] = ("El modo de la rueda debe ser libre, por pasos, automático o sin cambios.", "El mode de la roda ha de ser lliure, per passos, automàtic o sense canvis."),
        ["The automatic wheel threshold must be between 1 and 254."] = ("El umbral de la rueda automática debe estar entre 1 y 254.", "El llindar de la roda automàtica ha d'estar entre 1 i 254."),
        ["A mouse control identifier cannot be zero."] = ("El identificador de un control del ratón no puede ser cero.", "L'identificador d'un control del ratolí no pot ser zero."),
        ["Restoring the previous mouse settings."] = ("Restaurando los ajustes anteriores del ratón.", "Restaurant la configuració anterior del ratolí."),
        ["Always on Top"] = ("Siempre encima", "Sempre al davant"),
        ["No eligible window is active."] = ("No hay una ventana compatible activa.", "No hi ha cap finestra compatible activa."),
        ["This window requires administrator permissions. Restart Llampec as administrator to pin it."] = ("Esta ventana requiere permisos de administrador. Reinicia Llampec como administrador para fijarla.", "Esta finestra requerix permisos d'administrador. Reinicia Llampec com a administrador per a fixar-la."),
        ["Restart as administrator"] = ("Reiniciar como administrador", "Reinicia com a administrador"),
        ["Administrator restart was cancelled."] = ("Se ha cancelado el reinicio como administrador.", "S'ha cancel·lat el reinici com a administrador."),
        ["Could not restart Llampec as administrator."] = ("No se ha podido reiniciar Llampec como administrador.", "No s'ha pogut reiniciar Llampec com a administrador."),
        ["This window has an always-on-top companion window. Close it before pinning."] = ("Esta aplicación tiene una ventana auxiliar siempre encima. Ciérrala antes de fijarla.", "Esta aplicació té una finestra auxiliar sempre al davant. Tanca-la abans de fixar-la."),
        ["The window is not responding. Try again when it responds."] = ("La ventana no responde. Inténtalo de nuevo cuando responda.", "La finestra no respon. Torna a provar-ho quan responga."),
        ["Pin: {0}"] = ("Fijar: {0}", "Fixa: {0}"),
        ["Unpin: {0}"] = ("Desfijar: {0}", "Desfixa: {0}"),
        ["{0} pinned"] = ("{0} fijadas", "{0} fixades"),
        ["Choose a window"] = ("Elige una ventana", "Tria una finestra"),
        ["Window tracking is unavailable. Choose a window from the list."] = ("No se puede seguir la ventana activa. Elige una de la lista.", "No es pot seguir la finestra activa. Tria'n una de la llista."),
        ["Could not pin this window."] = ("No se ha podido fijar esta ventana.", "No s’ha pogut fixar esta finestra."),
        ["Could not unpin this window."] = ("No se ha podido desfijar esta ventana.", "No s’ha pogut desfixar esta finestra."),
        ["This window is already kept on top by another application."] = ("Otra aplicación ya mantiene esta ventana siempre encima.", "Una altra aplicació ja manté esta finestra sempre al davant."),
        ["This window is no longer available."] = ("Esta ventana ya no está disponible.", "Esta finestra ja no està disponible."),
        ["The window is no longer available."] = ("La ventana ya no está disponible.", "La finestra ja no està disponible."),
        ["Could not show the window border."] = ("No se ha podido mostrar el borde de la ventana.", "No s’ha pogut mostrar la vora de la finestra."),
        ["Appearance"] = ("Apariencia", "Aparença"),
        ["Show border"] = ("Mostrar borde", "Mostra la vora"),
        ["Border thickness"] = ("Grosor del borde", "Gruix de la vora"),
        ["Enter a whole number from 1 to 8."] = ("Introduce un número entero del 1 al 8.", "Introduïx un nombre enter de l’1 al 8."),
        ["Shortcut"] = ("Atajo de teclado", "Drecera de teclat"),
        ["Unpin all"] = ("Desfijar todas", "Desfixa-les totes"),
        ["Refresh windows"] = ("Actualizar ventanas", "Actualitza les finestres"),
        ["No windows available."] = ("No hay ventanas disponibles.", "No hi ha finestres disponibles."),
        ["Shortcut is already in use."] = ("El atajo de teclado ya está en uso.", "La drecera de teclat ja està en ús."),
        ["Enter a valid shortcut or leave it empty to disable it."] = ("Introduce un atajo válido o déjalo vacío para desactivarlo.", "Introduïx una drecera vàlida o deixa el camp buit per a desactivar-la."),
        ["Pins or unpins the active window. Leave empty to disable."] = ("Fija o desfija la ventana activa. Déjalo vacío para desactivar el atajo.", "Fixa o desfixa la finestra activa. Deixa el camp buit per a desactivar la drecera."),
        ["Shortcut disabled."] = ("Atajo de teclado desactivado.", "Drecera de teclat desactivada."),
        ["Shortcut saved."] = ("Atajo de teclado guardado.", "Drecera de teclat guardada."),
        ["Acknowledgements"] = ("Agradecimientos", "Agraïments"),
        ["Always on Top inspired by Microsoft PowerToys."] = ("Siempre encima se inspira en Microsoft PowerToys.", "Sempre al davant s’inspira en Microsoft PowerToys."),
        ["Caffeine mode"] = ("Modo cafeína", "Mode cafeïna"),
        ["Duration"] = ("Duración", "Duració"),
        ["Indefinite"] = ("Indefinido", "Indefinit"),
        ["1 hour"] = ("1 hora", "1 hora"),
        ["2 hours"] = ("2 horas", "2 hores"),
        ["3 hours"] = ("3 horas", "3 hores"),
        ["Custom"] = ("Personalizado", "Personalitzat"),
        ["Minutes (1–1440)"] = ("Minutos (1–1440)", "Minuts (1–1440)"),
        ["Keep the screen on"] = ("Mantener la pantalla encendida", "Mantín la pantalla encesa"),
        ["Until {0}"] = ("Hasta las {0}", "Fins a les {0}"),
        ["Activate"] = ("Activar", "Activa"),
        ["Deactivate"] = ("Desactivar", "Desactiva"),
        ["Apply and restart"] = ("Aplicar y reiniciar", "Aplica i reinicia"),
        ["Enter a whole number from 1 to 1440."] = ("Introduce un número entero del 1 al 1440.", "Introduïx un nombre enter de l’1 al 1440."),
        ["Could not activate caffeine mode."] = ("No se ha podido activar el modo cafeína.", "No s’ha pogut activar el mode cafeïna."),
        ["Could not save settings."] = ("No se han podido guardar los ajustes.", "No s’ha pogut guardar la configuració."),
        ["Prevents automatic sleep. Manual sleep ends the session. Windows may limit it on battery."] = ("Evita la suspensión automática. Suspender manualmente finaliza la sesión. Windows puede limitarlo con batería.", "Evita la suspensió automàtica. Suspendre manualment finalitza la sessió. Windows pot limitar-ho amb bateria."),
        ["Settings"] = ("Ajustes", "Configuració"),
        ["Language"] = ("Idioma", "Idioma"),
        ["Use Windows language"] = ("Usar el idioma de Windows", "Usa l’idioma de Windows"),
        ["Start with Windows"] = ("Iniciar con Windows", "Inicia amb Windows"),
        ["Opens in the notification area when you sign in."] = ("Se inicia en el área de notificación al entrar en tu sesión.", "S’inicia a l’àrea de notificació en entrar a la sessió."),
        ["Windows can also disable startup. After moving Llampec, open it once to update its startup location."] = ("Windows también puede desactivar el inicio. Si mueves Llampec, ábrelo una vez para actualizar su ruta de inicio.", "Windows també pot desactivar l’inici. Si mous Llampec, obri’l una vegada per a actualitzar-ne la ruta d’inici."),
        ["Windows startup apps"] = ("Aplicaciones de inicio de Windows", "Aplicacions d’inici de Windows"),
        ["Could not update startup registration."] = ("No se ha podido cambiar el inicio con Windows.", "No s’ha pogut canviar l’inici amb Windows."),
        ["Could not open Windows Settings."] = ("No se han podido abrir los ajustes de Windows.", "No s’ha pogut obrir la configuració de Windows."),
        ["Reorder buttons"] = ("Reordenar botones", "Reordena els botons"),
        ["Drag rows to change their order, or select one and use the arrows. The panel fills from left to right."] = ("Arrastra las filas o selecciona una y usa las flechas. El panel se ordena de izquierda a derecha.", "Arrossega les files o selecciona’n una i usa les fletxes. El panell s’ordena d’esquerra a dreta."),
        ["Move up"] = ("Subir", "Puja"), ["Move down"] = ("Bajar", "Baixa"),
        ["Save"] = ("Guardar", "Guarda"), ["Cancel"] = ("Cancelar", "Cancel·la"),
        ["Back"] = ("Atrás", "Enrere"), ["Menu"] = ("Menú", "Menú"),
        ["About Llampec"] = ("Acerca de Llampec", "Quant a Llampec"),
        ["Exit"] = ("Salir", "Ix"), ["Close"] = ("Cerrar", "Tanca"),
        ["Version"] = ("Versión", "Versió"),
        ["On"] = ("Activado", "Activat"), ["Off"] = ("Desactivado", "Desactivat"),
        ["Dark mode"] = ("Modo oscuro", "Mode fosc"), ["Light mode"] = ("Modo claro", "Mode clar"),
        ["Dark"] = ("Oscuro", "Fosc"), ["Light"] = ("Claro", "Clar"),
        ["Dark in {0}"] = ("Oscuro en {0}", "Fosc en {0}"),
        ["Light in {0}"] = ("Claro en {0}", "Clar en {0}"),
        ["{0} min"] = ("{0} min", "{0} min"),
        ["{0} h"] = ("{0} h", "{0} h"),
        ["{0} h {1} min"] = ("{0} h {1} min", "{0} h {1} min"),
        ["Turn off display"] = ("Apagar pantalla", "Apaga la pantalla"),
        ["Auto-hide taskbar"] = ("Ocultar barra de tareas", "Oculta la barra de tasques"),
        ["Multiple displays"] = ("Varias pantallas", "Diverses pantalles"),
        ["PC screen only"] = ("Solo pantalla del PC", "Només la pantalla del PC"),
        ["Second screen only"] = ("Solo segunda pantalla", "Només la segona pantalla"),
        ["Duplicate"] = ("Duplicar", "Duplica"), ["Extend"] = ("Extender", "Estén"),
        ["Not supported"] = ("No compatible", "No compatible"), ["All on"] = ("Todas activadas", "Totes activades"),
        ["Some displays are on"] = ("Algunas pantallas están activadas", "Algunes pantalles estan activades"),
        ["{0} options"] = ("Opciones de {0}", "Opcions de {0}"),
        ["{0} of {1}"] = ("{0} de {1}", "{0} de {1}"),
        ["Schedule"] = ("Programación", "Programació"),
        ["Light and dark times must differ."] = ("Las horas de modo claro y oscuro deben ser distintas.", "Les hores de mode clar i fosc han de ser diferents."),
        ["Enter a latitude from -90 to 90 and a longitude from -180 to 180."] = ("Introduce una latitud entre -90 y 90 y una longitud entre -180 y 180.", "Introduïx una latitud entre -90 i 90 i una longitud entre -180 i 180."),
        ["Unknown schedule mode."] = ("Modo de programación desconocido.", "Mode de programació desconegut."),
        ["Fixed hours"] = ("Horario fijo", "Horari fix"),
        ["Sunrise / sunset"] = ("Amanecer / anochecer", "Eixida / posta del sol"),
        ["Latitude"] = ("Latitud", "Latitud"), ["Longitude"] = ("Longitud", "Longitud"),
        ["Light at sunrise, dark at sunset. Coordinates are saved for offline calculations."] = ("Modo claro al amanecer y oscuro al anochecer. Las coordenadas se guardan para calcularlo sin conexión.", "Mode clar a l’eixida del sol i fosc a la posta. Les coordenades es guarden per a calcular-ho sense connexió."),
        ["Use current location"] = ("Usar ubicación actual", "Usa la ubicació actual"),
        ["Location detected. Apply to save."] = ("Ubicación detectada. Pulsa Aplicar para guardarla.", "Ubicació detectada. Prem Aplica per a guardar-la."),
        ["Location unavailable or permission denied. Enter coordinates manually."] = ("Ubicación no disponible o sin permiso. Introduce las coordenadas manualmente.", "Ubicació no disponible o sense permís. Introduïx les coordenades manualment."),
        ["Location unavailable: "] = ("Ubicación no disponible: ", "Ubicació no disponible: "),
        ["Changes Windows and apps while Llampec is running. A manual toggle lasts until the next scheduled change."] = ("Cambia Windows y las aplicaciones mientras Llampec está en ejecución. Un cambio manual dura hasta el siguiente cambio programado.", "Canvia Windows i les aplicacions mentre Llampec està en execució. Un canvi manual dura fins al següent canvi programat."),
        ["Apply"] = ("Aplicar", "Aplica"),
        ["Could not save settings. Check access to the Llampec settings folder."] = ("No se han podido guardar los ajustes. Comprueba el acceso a la carpeta de ajustes de Llampec.", "No s’ha pogut guardar la configuració. Comprova l’accés a la carpeta de configuració de Llampec."),
        ["Apply to save changes."] = ("Pulsa Aplicar para guardar los cambios.", "Prem Aplica per a guardar els canvis."),
        ["Schedule is off."] = ("Programación desactivada.", "Programació desactivada."),
        ["Polar day/night: no sunrise or sunset today. Checked again tomorrow."] = ("Día o noche polar: hoy no hay amanecer o anochecer. Se comprobará mañana.", "Dia o nit polar: hui no hi ha eixida o posta del sol. Es comprovarà demà."),
        ["Next: {0} · {1:g}"] = ("Siguiente: {0} · {1:g}", "Següent: {0} · {1:g}"),
    };
}
